name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name (e.g., v1.2.3)"
        required: true
      release_name:
        description: "Release title (defaults to tag name)"
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    # ← ここが重要：Environment 名を指定（あなたの画面だと GH_TOKEN という名前）
    environment: CODEX-VIEWER-ENV

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.8.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
          cache: pnpm
          # （任意）npm 発行なら registry を明示
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Configure npm auth token
        env:
          # Environment に置いた NPM_TOKEN を受け取る（environment 指定が必須）
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -z "$NPM_TOKEN" ]; then
            echo "NPM_TOKEN secret is required to publish" >&2
            exit 1
          fi
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm config set always-auth true

      - name: Publish to npm
        env:
          # setup-node の規約：NODE_AUTH_TOKEN があれば publish で使われる
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public

      - name: Determine release metadata
        id: meta
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag_name }}" >> "$GITHUB_OUTPUT"
            if [ -n "${{ github.event.inputs.release_name }}" ]; then
              echo "name=${{ github.event.inputs.release_name }}" >> "$GITHUB_OUTPUT"
            else
              echo "name=${{ github.event.inputs.tag_name }}" >> "$GITHUB_OUTPUT"
            fi
            echo "target=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
            echo "name=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
            echo "target=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          # ここは secrets.GITHUB_TOKEN ではなく github.token を使う
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          release_name: ${{ steps.meta.outputs.name }}
          target_commitish: ${{ steps.meta.outputs.target }}
          body: "Automated release for ${{ steps.meta.outputs.tag }}"
